# Generated by Django 2.2.5 on 2019-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infoname', models.CharField(blank=True, max_length=256)),
                ('info', models.TextField()),
                ('img', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
